### ISSUE TITLE
Failed to pull down source code

### ISSUE THREAD

**Issue by m0609shim** [ispras/llv8#14]
Hi, everyone.

When I try to pull down source code following your instruction.
It shows plenty of conflicts during step 4.
1. fetch v8
2. cd v8
3. git remote add llv8 https://github.com/ispras/llv8.git
4. git pull llv8 llv8
5. git checkout llv8
6. gclient sync

I guess your code doesn't work on latest V8 source.
Can you fix it or give me information about commit I should work on?

Thanks.
MyeongBo Shim.

**Comment by vivanishin** [comment]
All right. We don't really need to pull. Just check out the llv8 branch for steps 4 and 5 combined:
`git checkout -b llv8 llv8/llv8`

bb45a3f4d3ff685e4a86a3d1bfc857e020d70e38 fixes the build instructions in README
